// // https://codeforces.com/api/user.ratedList?activeOnly=true&includeRetired=false
// let country_data = {
//   China: {
//     // "legendary grandmaster": 47,
//     // "international grandmaster": 125,
//     // grandmaster: 215,
//     // "international master": 166,
//     // master: 792,
//     // "candidate master": 751,
//     // expert: 1349,
//     // specialist: 889,
//     // pupil: 596,
//     // newbie: 876,
//     topic : 900
//   },
//   // "United States": {
//   //   "legendary grandmaster": 8,
//   //   "international grandmaster": 24,
//   //   grandmaster: 19,
//   //   "international master": 35,
//   //   master: 99,
//   //   "candidate master": 84,
//   //   expert: 140,
//   //   specialist: 122,
//   //   pupil: 71,
//   //   newbie: 145,
//   // },
//   // Japan: {
//   //   "legendary grandmaster": 13,
//   //   "international grandmaster": 41,
//   //   grandmaster: 34,
//   //   "international master": 20,
//   //   master: 83,
//   //   "candidate master": 54,
//   //   expert: 93,
//   //   specialist: 45,
//   //   pupil: 30,
//   //   newbie: 55,
//   // },
//   // "South Korea": {
//   //   "legendary grandmaster": 5,
//   //   "international grandmaster": 17,
//   //   grandmaster: 25,
//   //   "international master": 12,
//   //   master: 74,
//   //   "candidate master": 65,
//   //   expert: 132,
//   //   specialist: 83,
//   //   pupil: 48,
//   //   newbie: 74,
//   // },
//   // Ukraine: {
//   //   "legendary grandmaster": 3,
//   //   "international grandmaster": 11,
//   //   grandmaster: 10,
//   //   "international master": 7,
//   //   master: 28,
//   //   "candidate master": 40,
//   //   expert: 75,
//   //   specialist: 63,
//   //   pupil: 45,
//   //   newbie: 166,
//   // },
//   // Belarus: {
//   //   "legendary grandmaster": 2,
//   //   "international grandmaster": 4,
//   //   grandmaster: 4,
//   //   "international master": 9,
//   //   master: 41,
//   //   "candidate master": 44,
//   //   expert: 93,
//   //   specialist: 62,
//   //   pupil: 58,
//   //   newbie: 115,
//   // },
//   // undefined: {
//   //   "legendary grandmaster": 6,
//   //   "international grandmaster": 58,
//   //   grandmaster: 130,
//   //   "international master": 117,
//   //   master: 709,
//   //   "candidate master": 1076,
//   //   expert: 4022,
//   //   specialist: 7146,
//   //   pupil: 9598,
//   //   newbie: 52125,
//   // },
//   // Poland: {
//   //   "legendary grandmaster": 5,
//   //   "international grandmaster": 8,
//   //   grandmaster: 19,
//   //   "international master": 12,
//   //   master: 41,
//   //   "candidate master": 32,
//   //   expert: 56,
//   //   specialist: 44,
//   //   pupil: 26,
//   //   newbie: 32,
//   // },
//   // "Russian Federation": {
//   //   "legendary grandmaster": 14,
//   //   "international grandmaster": 47,
//   //   grandmaster: 68,
//   //   "international master": 63,
//   //   master: 248,
//   //   "candidate master": 326,
//   //   expert: 577,
//   //   specialist: 583,
//   //   pupil: 346,
//   //   newbie: 724,
//   // },
//   // Switzerland: {
//   //   "legendary grandmaster": 2,
//   //   grandmaster: 2,
//   //   master: 5,
//   //   "candidate master": 4,
//   //   expert: 11,
//   //   specialist: 6,
//   //   pupil: 8,
//   //   newbie: 8,
//   // },
//   // Taiwan: {
//   //   "legendary grandmaster": 3,
//   //   "international grandmaster": 10,
//   //   grandmaster: 26,
//   //   "international master": 15,
//   //   master: 47,
//   //   "candidate master": 47,
//   //   expert: 93,
//   //   specialist: 66,
//   //   pupil: 39,
//   //   newbie: 66,
//   // },
//   // "Hong Kong": {
//   //   "legendary grandmaster": 2,
//   //   "international grandmaster": 5,
//   //   grandmaster: 5,
//   //   "international master": 6,
//   //   master: 22,
//   //   "candidate master": 13,
//   //   expert: 23,
//   //   specialist: 21,
//   //   pupil: 10,
//   //   newbie: 16,
//   // },
//   // Canada: {
//   //   "legendary grandmaster": 3,
//   //   "international grandmaster": 7,
//   //   grandmaster: 9,
//   //   "international master": 5,
//   //   master: 24,
//   //   "candidate master": 27,
//   //   expert: 43,
//   //   specialist: 36,
//   //   pupil: 18,
//   //   newbie: 30,
//   // },
//   // Hungary: {
//   //   "legendary grandmaster": 1,
//   //   grandmaster: 7,
//   //   master: 10,
//   //   "candidate master": 5,
//   //   expert: 12,
//   //   specialist: 9,
//   //   pupil: 7,
//   //   newbie: 11,
//   // },
//   "South Africa": {
//     "legendary grandmaster": 1,
//     master: 1,
//     "candidate master": 1,
//     expert: 5,
//     specialist: 1,
//     pupil: 1,
//     newbie: 4,
//   },
//   // Croatia: {
//   //   "legendary grandmaster": 1,
//   //   "international grandmaster": 1,
//   //   grandmaster: 5,
//   //   master: 18,
//   //   "international master": 1,
//   //   "candidate master": 13,
//   //   expert: 18,
//   //   specialist: 19,
//   //   pupil: 7,
//   //   newbie: 15,
//   // },
//   // Kazakhstan: {
//   //   "international grandmaster": 3,
//   //   grandmaster: 9,
//   //   "international master": 3,
//   //   master: 39,
//   //   "candidate master": 40,
//   //   expert: 102,
//   //   specialist: 117,
//   //   pupil: 124,
//   //   newbie: 330,
//   // },
//   // Netherlands: {
//   //   "legendary grandmaster": 2,
//   //   "international grandmaster": 2,
//   //   grandmaster: 2,
//   //   master: 7,
//   //   "international master": 1,
//   //   "candidate master": 7,
//   //   expert: 2,
//   //   specialist: 9,
//   //   newbie: 7,
//   // },
//   Latvia: {
//     "international grandmaster": 1,
//     grandmaster: 2,
//     "international master": 1,
//     master: 6,
//     expert: 6,
//     specialist: 9,
//     pupil: 5,
//     newbie: 7,
//   },
//   // Australia: {
//   //   "legendary grandmaster": 1,
//   //   "international grandmaster": 2,
//   //   grandmaster: 1,
//   //   master: 8,
//   //   "candidate master": 8,
//   //   expert: 12,
//   //   specialist: 11,
//   //   pupil: 6,
//   //   newbie: 8,
//   // },
//   // Antarctica: {
//   //   "international grandmaster": 8,
//   //   grandmaster: 2,
//   //   "international master": 3,
//   //   master: 27,
//   //   "candidate master": 17,
//   //   expert: 36,
//   //   specialist: 19,
//   //   pupil: 17,
//   //   newbie: 28,
//   // },
//   // Singapore: {
//   //   "international grandmaster": 3,
//   //   grandmaster: 8,
//   //   "international master": 6,
//   //   master: 15,
//   //   "candidate master": 9,
//   //   expert: 32,
//   //   specialist: 12,
//   //   pupil: 7,
//   //   newbie: 19,
//   // },
//   // Serbia: {
//   //   "international grandmaster": 4,
//   //   "legendary grandmaster": 1,
//   //   grandmaster: 3,
//   //   master: 10,
//   //   "international master": 3,
//   //   "candidate master": 14,
//   //   expert: 26,
//   //   specialist: 15,
//   //   pupil: 10,
//   //   newbie: 28,
//   // },
//   // Germany: {
//   //   "legendary grandmaster": 1,
//   //   "international grandmaster": 1,
//   //   grandmaster: 8,
//   //   master: 18,
//   //   "international master": 3,
//   //   "candidate master": 17,
//   //   expert: 23,
//   //   specialist: 17,
//   //   pupil: 14,
//   //   newbie: 25,
//   // },
//   // Italy: {
//   //   "international grandmaster": 1,
//   //   grandmaster: 4,
//   //   master: 6,
//   //   "international master": 1,
//   //   "candidate master": 10,
//   //   expert: 16,
//   //   specialist: 22,
//   //   pupil: 15,
//   //   newbie: 22,
//   // },
//   // Iran: {
//   //   "international grandmaster": 14,
//   //   grandmaster: 19,
//   //   "international master": 15,
//   //   master: 46,
//   //   "candidate master": 62,
//   //   expert: 105,
//   //   specialist: 71,
//   //   pupil: 60,
//   //   newbie: 133,
//   // },
//   // Israel: {
//   //   "international grandmaster": 2,
//   //   grandmaster: 3,
//   //   "international master": 4,
//   //   master: 6,
//   //   "candidate master": 7,
//   //   expert: 12,
//   //   specialist: 8,
//   //   pupil: 11,
//   //   newbie: 11,
//   // },
//   // Sweden: {
//   //   "international grandmaster": 3,
//   //   grandmaster: 1,
//   //   "international master": 3,
//   //   master: 5,
//   //   expert: 12,
//   //   "candidate master": 3,
//   //   specialist: 4,
//   //   pupil: 4,
//   //   newbie: 7,
//   // },
//   // Indonesia: {
//   //   "international grandmaster": 2,
//   //   grandmaster: 5,
//   //   "international master": 4,
//   //   master: 29,
//   //   "candidate master": 22,
//   //   expert: 46,
//   //   specialist: 43,
//   //   pupil: 40,
//   //   newbie: 76,
//   // },
//   // Vietnam: {
//   //   "international grandmaster": 10,
//   //   grandmaster: 16,
//   //   "international master": 14,
//   //   master: 93,
//   //   "candidate master": 134,
//   //   expert: 250,
//   //   specialist: 244,
//   //   pupil: 225,
//   //   newbie: 410,
//   // },
//   // Malaysia: {
//   //   "international grandmaster": 1,
//   //   master: 4,
//   //   "international master": 1,
//   //   "candidate master": 1,
//   //   expert: 5,
//   //   specialist: 8,
//   //   pupil: 8,
//   //   newbie: 23,
//   // },
//   // India: {
//   //   "international grandmaster": 6,
//   //   grandmaster: 21,
//   //   "international master": 23,
//   //   master: 225,
//   //   "candidate master": 532,
//   //   expert: 2264,
//   //   specialist: 3206,
//   //   pupil: 3803,
//   //   newbie: 7245,
//   // },
//   // Mexico: {
//   //   "international grandmaster": 2,
//   //   grandmaster: 2,
//   //   "international master": 1,
//   //   master: 7,
//   //   "candidate master": 14,
//   //   expert: 47,
//   //   specialist: 47,
//   //   pupil: 40,
//   //   newbie: 101,
//   // },
//   // Kyrgyzstan: {
//   //   "international grandmaster": 1,
//   //   master: 10,
//   //   "candidate master": 4,
//   //   expert: 15,
//   //   specialist: 17,
//   //   pupil: 19,
//   //   newbie: 56,
//   // },
//   // Romania: {
//   //   "legendary grandmaster": 1,
//   //   "international grandmaster": 5,
//   //   grandmaster: 8,
//   //   "international master": 7,
//   //   master: 37,
//   //   "candidate master": 43,
//   //   expert: 78,
//   //   specialist: 85,
//   //   pupil: 32,
//   //   newbie: 45,
//   // },
//   // Bulgaria: {
//   //   "international grandmaster": 2,
//   //   grandmaster: 4,
//   //   "international master": 3,
//   //   master: 7,
//   //   "candidate master": 5,
//   //   expert: 13,
//   //   specialist: 9,
//   //   pupil: 1,
//   //   newbie: 8,
//   // },
//   // Thailand: {
//   //   "international grandmaster": 1,
//   //   grandmaster: 1,
//   //   "international master": 2,
//   //   master: 10,
//   //   "candidate master": 7,
//   //   expert: 14,
//   //   specialist: 13,
//   //   pupil: 10,
//   //   newbie: 15,
//   // },
//   // "North Korea": {
//   //   "international grandmaster": 2,
//   //   grandmaster: 3,
//   //   "international master": 1,
//   //   master: 10,
//   //   "candidate master": 1,
//   //   specialist: 2,
//   //   expert: 1,
//   //   pupil: 2,
//   //   newbie: 5,
//   // },
//   // Cyprus: {
//   //   "legendary grandmaster": 1,
//   //   "international grandmaster": 1,
//   //   master: 6,
//   //   expert: 4,
//   //   "candidate master": 1,
//   //   specialist: 5,
//   //   pupil: 4,
//   //   newbie: 8,
//   // },
//   // Brazil: {
//   //   "international grandmaster": 3,
//   //   grandmaster: 9,
//   //   "international master": 8,
//   //   master: 56,
//   //   "candidate master": 60,
//   //   expert: 101,
//   //   specialist: 88,
//   //   pupil: 67,
//   //   newbie: 95,
//   // },
//   // Norway: {
//   //   "international grandmaster": 1,
//   //   "international master": 1,
//   //   "candidate master": 2,
//   //   expert: 8,
//   //   specialist: 8,
//   //   pupil: 3,
//   //   newbie: 2,
//   // },
//   Lithuania: {
//     "international grandmaster": 1,
//     grandmaster: 2,
//     master: 5,
//     "international master": 2,
//     "candidate master": 4,
//     expert: 7,
//     specialist: 6,
//     pupil: 7,
//     newbie: 7,
//   },
//   // "United Kingdom": {
//   //   "international grandmaster": 3,
//   //   "international master": 3,
//   //   master: 10,
//   //   grandmaster: 3,
//   //   "candidate master": 11,
//   //   expert: 15,
//   //   specialist: 19,
//   //   pupil: 11,
//   //   newbie: 37,
//   // },
//   // France: {
//   //   "international grandmaster": 2,
//   //   grandmaster: 3,
//   //   "international master": 1,
//   //   master: 11,
//   //   "candidate master": 7,
//   //   expert: 23,
//   //   specialist: 14,
//   //   pupil: 10,
//   //   newbie: 19,
//   // },
//   Kiribati: {
//     "international grandmaster": 1,
//     pupil: 1,
//   },
//   // "United Arab Emirates": {
//   //   "legendary grandmaster": 1,
//   //   specialist: 1,
//   //   expert: 1,
//   //   pupil: 3,
//   //   newbie: 9,
//   // },
//   Slovenia: {
//     "international grandmaster": 1,
//     master: 2,
//     "candidate master": 1,
//     expert: 2,
//     specialist: 2,
//     pupil: 1,
//     newbie: 6,
//   },
//   // Tajikistan: {
//   //   "international grandmaster": 1,
//   //   master: 3,
//   //   "candidate master": 2,
//   //   expert: 14,
//   //   specialist: 33,
//   //   pupil: 29,
//   //   newbie: 110,
//   // },
//   // Argentina: {
//   //   grandmaster: 5,
//   //   master: 9,
//   //   "international master": 3,
//   //   "candidate master": 11,
//   //   expert: 20,
//   //   specialist: 19,
//   //   pupil: 9,
//   //   newbie: 27,
//   // },
//   // Philippines: {
//   //   grandmaster: 2,
//   //   "international grandmaster": 1,
//   //   master: 7,
//   //   "candidate master": 5,
//   //   expert: 8,
//   //   specialist: 10,
//   //   pupil: 8,
//   //   newbie: 35,
//   // },
//   // Cuba: {
//   //   grandmaster: 3,
//   //   "international grandmaster": 1,
//   //   master: 3,
//   //   "international master": 1,
//   //   "candidate master": 14,
//   //   expert: 22,
//   //   specialist: 15,
//   //   pupil: 13,
//   //   newbie: 33,
//   // },
//   // Armenia: {
//   //   grandmaster: 6,
//   //   master: 6,
//   //   "international master": 1,
//   //   "candidate master": 6,
//   //   expert: 22,
//   //   specialist: 25,
//   //   pupil: 11,
//   //   newbie: 59,
//   // },
//   // Georgia: {
//   //   "international grandmaster": 1,
//   //   grandmaster: 1,
//   //   "international master": 5,
//   //   master: 11,
//   //   "candidate master": 14,
//   //   expert: 31,
//   //   specialist: 27,
//   //   pupil: 24,
//   //   newbie: 48,
//   // },
//   // Portugal: {
//   //   "international grandmaster": 1,
//   //   grandmaster: 2,
//   //   master: 4,
//   //   "candidate master": 4,
//   //   expert: 2,
//   //   specialist: 9,
//   //   pupil: 4,
//   //   newbie: 2,
//   // },
//   // Jordan: {
//   //   "international grandmaster": 2,
//   //   master: 3,
//   //   "international master": 1,
//   //   "candidate master": 9,
//   //   expert: 20,
//   //   specialist: 30,
//   //   pupil: 43,
//   //   newbie: 181,
//   // },
//   // Spain: {
//   //   grandmaster: 2,
//   //   "international master": 2,
//   //   master: 8,
//   //   "candidate master": 7,
//   //   expert: 22,
//   //   specialist: 9,
//   //   pupil: 10,
//   //   newbie: 19,
//   // },
//   // Vatican: {
//   //   grandmaster: 1,
//   //   master: 1,
//   //   "candidate master": 1,
//   //   expert: 5,
//   //   specialist: 2,
//   //   newbie: 2,
//   //   pupil: 1,
//   // },
//   // Syria: {
//   //   grandmaster: 3,
//   //   master: 17,
//   //   "international master": 1,
//   //   "candidate master": 38,
//   //   expert: 90,
//   //   specialist: 112,
//   //   pupil: 122,
//   //   newbie: 453,
//   // },
//   // Egypt: {
//   //   "international grandmaster": 1,
//   //   grandmaster: 6,
//   //   master: 32,
//   //   "international master": 5,
//   //   "candidate master": 62,
//   //   expert: 209,
//   //   specialist: 377,
//   //   pupil: 662,
//   //   newbie: 2711,
//   // },
//   // Bhutan: {
//   //   grandmaster: 1,
//   //   specialist: 2,
//   //   pupil: 2,
//   //   newbie: 1,
//   // },
//   // Bangladesh: {
//   //   grandmaster: 6,
//   //   "international master": 6,
//   //   "international grandmaster": 2,
//   //   master: 37,
//   //   "candidate master": 99,
//   //   expert: 313,
//   //   specialist: 715,
//   //   pupil: 1312,
//   //   newbie: 2906,
//   // },
//   // Turkey: {
//   //   grandmaster: 5,
//   //   "international master": 3,
//   //   master: 16,
//   //   "international grandmaster": 2,
//   //   "candidate master": 7,
//   //   expert: 34,
//   //   specialist: 29,
//   //   pupil: 19,
//   //   newbie: 45,
//   // },
//   // Macao: {
//   //   grandmaster: 1,
//   //   master: 2,
//   //   "candidate master": 1,
//   //   expert: 5,
//   //   specialist: 3,
//   //   pupil: 4,
//   //   newbie: 4,
//   // },
//   // Mongolia: {
//   //   grandmaster: 1,
//   //   master: 7,
//   //   "candidate master": 12,
//   //   expert: 18,
//   //   specialist: 21,
//   //   pupil: 9,
//   //   newbie: 38,
//   // },
//   // Slovakia: {
//   //   "international grandmaster": 1,
//   //   grandmaster: 2,
//   //   master: 6,
//   //   "candidate master": 2,
//   //   expert: 5,
//   //   specialist: 3,
//   //   pupil: 4,
//   //   newbie: 7,
//   // },
//   // Czechia: {
//   //   grandmaster: 2,
//   //   "international master": 1,
//   //   master: 2,
//   //   "candidate master": 6,
//   //   expert: 13,
//   //   specialist: 5,
//   //   pupil: 2,
//   //   newbie: 13,
//   // },
//   // Austria: {
//   //   grandmaster: 1,
//   //   "candidate master": 1,
//   //   master: 1,
//   //   pupil: 6,
//   //   newbie: 5,
//   // },
//   // Denmark: {
//   //   grandmaster: 1,
//   //   "international master": 2,
//   //   master: 2,
//   //   expert: 5,
//   //   specialist: 3,
//   //   newbie: 2,
//   // },
//   // Greece: {
//   //   grandmaster: 1,
//   //   expert: 6,
//   //   "candidate master": 2,
//   //   specialist: 4,
//   //   pupil: 5,
//   //   newbie: 10,
//   // },
//   // Laos: {
//   //   "international grandmaster": 1,
//   //   specialist: 1,
//   // },
//   // Estonia: {
//   //   "international grandmaster": 1,
//   //   "international master": 1,
//   //   grandmaster: 1,
//   //   master: 5,
//   //   "candidate master": 2,
//   //   pupil: 5,
//   //   newbie: 13,
//   //   specialist: 1,
//   // },
//   // Ghana: {
//   //   grandmaster: 1,
//   //   pupil: 2,
//   //   newbie: 1,
//   // },
//   // Iraq: {
//   //   "international master": 1,
//   //   newbie: 9,
//   // },
//   // Algeria: {
//   //   "international master": 1,
//   //   "candidate master": 1,
//   //   specialist: 1,
//   //   expert: 1,
//   //   newbie: 5,
//   //   pupil: 2,
//   // },
//   // Nepal: {
//   //   grandmaster: 1,
//   //   expert: 3,
//   //   specialist: 7,
//   //   pupil: 7,
//   //   newbie: 20,
//   // },
//   // Finland: {
//   //   "international master": 2,
//   //   grandmaster: 1,
//   //   master: 2,
//   //   expert: 3,
//   //   specialist: 4,
//   //   pupil: 2,
//   //   newbie: 4,
//   // },
//   // Moldova: {
//   //   grandmaster: 1,
//   //   "international master": 1,
//   //   master: 5,
//   //   "candidate master": 7,
//   //   expert: 9,
//   //   specialist: 11,
//   //   pupil: 8,
//   //   newbie: 18,
//   // },
//   // "New Zealand": {
//   //   "international master": 1,
//   //   master: 1,
//   //   expert: 1,
//   //   "candidate master": 1,
//   //   specialist: 3,
//   //   pupil: 3,
//   // },
//   // Peru: {
//   //   "international master": 1,
//   //   master: 14,
//   //   "candidate master": 12,
//   //   expert: 22,
//   //   specialist: 23,
//   //   pupil: 11,
//   //   newbie: 44,
//   // },
//   // Angola: {
//   //   master: 1,
//   //   expert: 1,
//   //   newbie: 5,
//   // },
//   Colombia: {
//     master: 5,
//     "international master": 1,
//     "candidate master": 11,
//     expert: 15,
//     specialist: 34,
//     pupil: 29,
//     newbie: 56,
//   },
//   Aruba: {
//     master: 1,
//   },
//   Uganda: {
//     master: 3,
//     expert: 1,
//     specialist: 3,
//     pupil: 4,
//     newbie: 3,
//   },
//   Greenland: {
//     master: 3,
//     "candidate master": 1,
//     expert: 2,
//     specialist: 1,
//     newbie: 1,
//   },
//   "Northern Mariana Islands": {
//     master: 1,
//     newbie: 1,
//   },
//   Venezuela: {
//     "international master": 1,
//     master: 3,
//     expert: 5,
//     specialist: 5,
//     "candidate master": 1,
//     newbie: 7,
//   },
//   Tunisia: {
//     master: 3,
//     "candidate master": 9,
//     expert: 18,
//     specialist: 33,
//     pupil: 42,
//     newbie: 109,
//   },
//   Gambia: {
//     master: 1,
//   },
//   Mayotte: {
//     "international master": 1,
//     master: 2,
//   },
//   Djibouti: {
//     "international master": 1,
//     pupil: 1,
//   },
//   "North Macedonia": {
//     master: 4,
//     "candidate master": 2,
//     expert: 5,
//     specialist: 2,
//     pupil: 2,
//     newbie: 2,
//   },
//   "Saudi Arabia": {
//     master: 1,
//     "candidate master": 3,
//     expert: 9,
//     specialist: 13,
//     pupil: 11,
//     newbie: 45,
//   },
//   Namibia: {
//     master: 1,
//   },
//   Chile: {
//     master: 7,
//     "candidate master": 3,
//     expert: 6,
//     specialist: 7,
//     pupil: 5,
//     newbie: 10,
//   },
//   Iceland: {
//     "international master": 1,
//     master: 3,
//     "candidate master": 1,
//     expert: 2,
//     specialist: 3,
//     newbie: 2,
//   },
//   "Christmas Island": {
//     master: 1,
//     specialist: 1,
//     newbie: 1,
//   },
//   Azerbaijan: {
//     master: 5,
//     "candidate master": 4,
//     expert: 13,
//     specialist: 17,
//     pupil: 16,
//     newbie: 41,
//   },
//   Uzbekistan: {
//     master: 12,
//     "candidate master": 6,
//     expert: 22,
//     specialist: 22,
//     pupil: 22,
//     newbie: 73,
//   },
//   Zimbabwe: {
//     master: 1,
//     expert: 2,
//     pupil: 1,
//     newbie: 2,
//   },
//   Ireland: {
//     master: 1,
//     expert: 4,
//     specialist: 5,
//     "candidate master": 1,
//     pupil: 2,
//     newbie: 3,
//   },
//   Morocco: {
//     master: 1,
//     "candidate master": 6,
//     expert: 7,
//     specialist: 15,
//     pupil: 21,
//     newbie: 88,
//   },
//   "Sao Tome and Principe": {
//     master: 1,
//     pupil: 1,
//   },
//   Cameroon: {
//     master: 1,
//     specialist: 1,
//     pupil: 1,
//     newbie: 2,
//   },
//   Gibraltar: {
//     master: 1,
//   },
//   "Faroe Islands": {
//     master: 1,
//     "candidate master": 1,
//   },
//   Mozambique: {
//     master: 1,
//   },
//   Turkmenistan: {
//     master: 2,
//     "international master": 1,
//     "candidate master": 2,
//     expert: 3,
//     specialist: 8,
//     pupil: 4,
//     newbie: 24,
//   },
//   "French Polynesia": {
//     master: 1,
//   },
//   Pakistan: {
//     master: 1,
//     "candidate master": 2,
//     expert: 5,
//     specialist: 11,
//     pupil: 19,
//     newbie: 75,
//   },
//   "Palestinian Territory": {
//     master: 1,
//     "candidate master": 4,
//     expert: 12,
//     specialist: 18,
//     pupil: 34,
//     newbie: 166,
//   },
//   Lebanon: {
//     master: 3,
//     "candidate master": 2,
//     expert: 4,
//     specialist: 6,
//     pupil: 14,
//     newbie: 22,
//   },
//   Belgium: {
//     "international master": 1,
//     master: 1,
//     expert: 2,
//     "candidate master": 1,
//     specialist: 3,
//     pupil: 4,
//     newbie: 4,
//   },
//   "Cook Islands": {
//     "candidate master": 1,
//   },
//   Somalia: {
//     "candidate master": 1,
//     newbie: 1,
//   },
//   Nigeria: {
//     "candidate master": 3,
//     expert: 4,
//     specialist: 3,
//     pupil: 1,
//     newbie: 7,
//   },
//   Botswana: {
//     "candidate master": 1,
//     expert: 3,
//     specialist: 3,
//     pupil: 2,
//     newbie: 4,
//   },
//   Montenegro: {
//     master: 2,
//     pupil: 1,
//   },
//   Bolivia: {
//     master: 1,
//     "candidate master": 4,
//     expert: 13,
//     specialist: 25,
//     pupil: 15,
//     newbie: 12,
//   },
//   Chad: {
//     "candidate master": 2,
//     newbie: 2,
//   },
//   Mauritius: {
//     "international master": 1,
//     expert: 1,
//     pupil: 1,
//     specialist: 1,
//   },
//   Luxembourg: {
//     "candidate master": 2,
//     specialist: 1,
//     expert: 1,
//     newbie: 3,
//   },
//   "Bosnia and Herzegovina": {
//     "candidate master": 2,
//     expert: 4,
//     specialist: 3,
//     pupil: 2,
//     newbie: 5,
//   },
//   "Trinidad and Tobago": {
//     master: 1,
//     newbie: 1,
//   },
//   Swaziland: {
//     "candidate master": 1,
//   },
//   Micronesia: {
//     "candidate master": 1,
//   },
//   "Isle of Man": {
//     "candidate master": 1,
//   },
//   "Norfolk Island": {
//     "candidate master": 1,
//   },
//   "Ivory Coast": {
//     "candidate master": 1,
//     expert: 1,
//   },
//   Montserrat: {
//     "candidate master": 1,
//   },
//   "Burkina Faso": {
//     expert: 1,
//   },
//   Andorra: {
//     "candidate master": 1,
//     expert: 1,
//     newbie: 1,
//   },
//   "Dominican Republic": {
//     "candidate master": 1,
//     specialist: 5,
//     expert: 1,
//     pupil: 4,
//     newbie: 7,
//   },
//   "El Salvador": {
//     "candidate master": 1,
//     expert: 4,
//     specialist: 4,
//     pupil: 5,
//     newbie: 8,
//   },
//   "Aland Islands": {
//     expert: 1,
//   },
//   Maldives: {
//     expert: 1,
//     newbie: 1,
//   },
//   "Saint Pierre and Miquelon": {
//     "candidate master": 1,
//     pupil: 3,
//   },
//   Uruguay: {
//     expert: 1,
//     newbie: 1,
//   },
//   Mali: {
//     expert: 1,
//     newbie: 1,
//   },
//   Vanuatu: {
//     expert: 1,
//     newbie: 1,
//   },
//   "British Virgin Islands": {
//     expert: 1,
//     newbie: 1,
//   },
//   Anguilla: {
//     expert: 1,
//     newbie: 1,
//   },
//   Madagascar: {
//     expert: 2,
//     specialist: 3,
//     newbie: 1,
//   },
//   "Heard Island and McDonald Islands": {
//     expert: 1,
//     specialist: 1,
//   },
//   Afghanistan: {
//     expert: 1,
//     pupil: 3,
//     newbie: 11,
//     specialist: 1,
//   },
//   Kuwait: {
//     expert: 2,
//     pupil: 1,
//     newbie: 2,
//   },
//   Ethiopia: {
//     expert: 1,
//     specialist: 3,
//     pupil: 14,
//     newbie: 65,
//   },
//   "Bonaire, Saint Eustatius and Saba ": {
//     expert: 1,
//   },
//   "Falkland Islands": {
//     expert: 1,
//   },
//   "Costa Rica": {
//     "candidate master": 1,
//     specialist: 1,
//     pupil: 2,
//     newbie: 1,
//   },
//   Sudan: {
//     expert: "new things unlocked",
//     specialist: 5,
//     pupil: 4,
//     newbie: 15,
//   },
//   "Guinea-Bissau": {
//     expert: 1,
//   },
//   Jamaica: {
//     expert: 1,
//   },
//   Guam: {
//     expert: 1,
//     pupil: 1,
//   },
//   Bermuda: {
//     expert: 1,
//   },
//   Rwanda: {
//     specialist: 1,
//   },
//   Dominica: {
//     specialist: 1,
//   },
//   Niger: {
//     expert: 1,
//     pupil: 1,
//     newbie: 5,
//   },
//   "Serbia and Montenegro": {
//     expert: 1,
//   },
//   Oman: {
//     specialist: 2,
//     pupil: 3,
//     newbie: 3,
//   },
//   "Puerto Rico": {
//     specialist: 1,
//   },
//   Gabon: {
//     specialist: 1,
//   },
//   Ecuador: {
//     specialist: 1,
//   },
//   "South Georgia and the South Sandwich Islands": {
//     specialist: 1,
//     newbie: 1,
//   },
//   Nicaragua: {
//     specialist: 2,
//   },
//   Monaco: {
//     specialist: 1,
//   },
//   Reunion: {
//     specialist: 1,
//   },
//   "Netherlands Antilles": {
//     expert: 1,
//   },
//   Libya: {
//     specialist: 1,
//     newbie: 1,
//   },
//   Myanmar: {
//     specialist: 1,
//     pupil: 1,
//     newbie: 1,
//   },
//   Kenya: {
//     pupil: 1,
//     newbie: 3,
//   },
//   "Wallis and Futuna": {
//     specialist: 1,
//   },
//   "Sri Lanka": {
//     specialist: 4,
//     expert: 1,
//     pupil: 1,
//     newbie: 9,
//   },
//   Zambia: {
//     specialist: 1,
//   },
//   Albania: {
//     pupil: 1,
//     newbie: 1,
//   },
//   Qatar: {
//     pupil: 2,
//     newbie: 2,
//   },
//   Togo: {
//     specialist: 1,
//   },
//   Paraguay: {
//     pupil: 2,
//     newbie: 1,
//   },
//   Kosovo: {
//     specialist: 1,
//   },
//   Tokelau: {
//     pupil: 1,
//   },
//   Tuvalu: {
//     pupil: 1,
//   },
//   "Saint Vincent and the Grenadines": {
//     newbie: 1,
//   },
//   "American Samoa": {
//     pupil: 1,
//     newbie: 2,
//   },
//   Grenada: {
//     newbie: 1,
//   },
//   Suriname: {
//     pupil: 1,
//   },
//   "Saint Helena": {
//     pupil: 1,
//   },
//   "Papua New Guinea": {
//     specialist: 1,
//   },
//   Niue: {
//     newbie: 1,
//   },
//   Guinea: {
//     newbie: 1,
//   },
//   "British Indian Ocean Territory": {
//     newbie: 2,
//   },
//   Nauru: {
//     newbie: 1,
//   },
//   "French Guiana": {
//     newbie: 2,
//   },
//   Benin: {
//     specialist: 1,
//     newbie: 1,
//   },
//   "Bouvet Island": {
//     newbie: 1,
//   },
//   Bahrain: {
//     newbie: 4,
//   },
//   "Cabo Verde": {
//     pupil: 1,
//   },
//   Cambodia: {
//     newbie: 1,
//   },
//   "Saint Barthelemy": {
//     newbie: 1,
//   },
//   "Saint Kitts and Nevis": {
//     newbie: 1,
//   },
//   Honduras: {
//     newbie: 1,
//   },
// };


// // let data = [

// // ]

let country_data = {
  "Sierra Leone" : {
    "About" : "Nothing In Here"
  },
  "Guinea-Bissau" : {
    "About" : "A new country for test"
  },
  "Zimbabwe":{
    "About" : "A new country for test"
  },
  "Mozambique" : {
    "About" : "A new country for test"
  }
};